---
services:
    app:
        container_name: simple-bank
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "${API_PORT:-8089}:8089"
        env_file:
            - .env
        volumes:
            - ./storage:/main/storage
        networks:
            - simple-bank
        depends_on:
            - postgres
            - migrate
        environment:
            - API_PORT=${API_PORT:-8089}
            - APP_ENV=local
            - APP_DEBUG=${APP_DEBUG:-true}
            - DB_HOST=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=${DB_PASSWORD:-admindev}
            - DB_PORT=5432
            - DB_NAME=${DB_NAME:-simple-bank}
    migrate:
        container_name: simple-bank-migration
        image: migrate/migrate:v4.17.0
        networks:
            - simple-bank
        volumes:
            - ./scripts/database/migration:/migrations # mount migration files
        entrypoint:
            [
                "migrate",
                "-path",
                "/migrations",
                "-database",
                "postgres://postgres:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable",
                "up",
            ]
        depends_on:
            - postgres
        environment:
            - DB_PASSWORD=${DB_PASSWORD:-admindev}
            - DB_NAME=${DB_NAME}
    postgres:
        container_name: postgres
        image: postgres:16.8-alpine3.20
        restart: always
        ports:
            - "${DB_EXPOSE_PORT:-5446}:5432"
        networks:
            - simple-bank
        env_file:
            - .env
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${DB_PASSWORD:-admindev}
            - POSTGRES_DB=${DB_NAME:-simple-bank}
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./docker/config/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    simple-bank:
        driver: bridge

volumes:
    postgres-data:
        driver: local
